subinclude("//tools/build_defs:tool")

tool(
    name = "jestconfig-transformer",
    srcs = ["jestconfig-transformer.mjs"],
    visibility = ["//..."],
    deps = [
        "//:package_json",
    ],
)
