ARCAT_VERSION = "1.0.3"

remote_file(
    name = "arcat",
    url = f"https://github.com/please-build/arcat/releases/download/v{ARCAT_VERSION}/arcat-{ARCAT_VERSION}-{CONFIG.HOSTOS}_{CONFIG.HOSTARCH}",
    binary = True,
    visibility = ["//..."],
)
